django/pytest/test01/booktest/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index$',views.index),
    url(r'^(\d+)$',views.detail),
]

django/pytest/test01/test01/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('booktest.urls')),
]

django/pytest/test01/booktest/models.py
from django.db import models

# Create your models here.
class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateField()
    def __str__(self):
        return "%d" % self.id

class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=100)
    hbook = models.ForeignKey(BookInfo)
    def __str__(self):
        return "%d" % self.id

django/pytest/test01/booktest/views.py
from django.shortcuts import render
from django.http import HttpResponse
from booktest.models import BookInfo,HeroInfo 

# 展示所有图书
def index(request):
    # 查询所有图书
    booklist = BookInfo.objects.all()
    # 将图书列表传递到模板中，然后渲染模板
    return render(request,'booktest/index.html',{'booklist':booklist})

# 书籍详情显示
def detail(request,id):
    # 根据图书编号查找对应的图书
    book = BookInfo.objects.get(pk=id)
    # 将图书信息放入模板进行渲染
    return render(request,'booktest/detail.html',{'book':book})

django/pytest/test01/templates/booktest/detail.html
<html>

<head>
    <title>英雄详情页</title>
</head>

<body>
    {#输出图书标题#}
    <h1>{{book.btitle}}</h1>
    <ul>
        {#通过关系找到这本书的所有英雄#} {%for hero in book.heroinfo_set.all%}
        <li>
            {{hero}} {#显示英雄的名字和描述#} {{hero.hname}} ----{{hero.hcontent}}
        </li>
        {%endfor%}
    </ul>
</body>

</html>

django/pytest/test01/templates/booktest/index.html
<html>

<head>
    <title>首页</title>
</head>

<body>
    <h1>图书列表</h1>
    <ul>
        {#遍历图书列表#} {%for book in booklist%}
        <li>
            {#输出图书名称，并设置超链接，链接地址是一个数字#}
            <a href="{{book.id}}">{{book.btitle}}</a>
        </li>{%endfor%}
    </ul>
</body>

</html>