django/pytest/test2/booktest/urls.py
from django.conf.urls import url
from booktest import views

urlpatterns = [
    url(r'^index$',views.index),
    url(r'^booklist$',views.booklist),
    url(r'^area$',views.area),
    # url(r'^(\d+)/(\d+)/$',views.index1),
    url(r'^(?P<parameter1>\d+)/(?P<parameter2>\d+)/$',views.index2),
    url(r'^method1/$',views.method1),
    url(r'^method2/$',views.method2),
    url(r'^method3/$',views.method3),
    url(r'^get$',views.get),
    url(r'^getwish$',views.getwish),
    # post 请求的POST属性：准备表单
    url(r'^post/$',views.post),
    # 获取表单提交的参数
    url(r'^post1/$',views.post1),
    url(r'^json1/$',views.json1),
    url(r'^json2/$',views.json2)
]

django/pytest/test2/test2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from booktest import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'',include('booktest.urls')),
    # url(r'^index$',views.index),
    # url(r'^booklist$',views.booklist),
    # url(r'^area$',views.area),
]

django/pytest/test2/booktest/models.py
from django.db import models


class BookInfoManager(models.Manager):
    '''自定义图书管理器类改变查询结果集'''
    def total(self):
        return super().all().filter(isDelete = False)
    
    def shuminghao(self,obj):
        '''给所有的书名加上书名号'''
        for i in obj:
            i.btitle = "《%s》"%i.btitle
        return obj

class BookInfo(models.Model):
    '''定义图书模型类BookInfo'''
    #使用和objects相同的名称来实例化，objects比原来的功能多了一个total方法
    objects = BookInfoManager()

    btitle = models.CharField(max_length=20)
    bpub_date = models.DateField() #发布日期
    bread = models.IntegerField(default=0) #阅读量
    bcommet = models.IntegerField(default=0) #评论量
    isDelete = models.BooleanField(default=False) #逻辑删除
    bcontext = models.CharField(max_length=100,null=True) #备注

    class Meta: #元信息类
        db_table = 'bookinfo' #指定表的名称


class HeroInfo(models.Model):
    '''定义英雄模型类HeroInfo'''
    hname = models.CharField(max_length=20) #英雄姓名
    hgender = models.BooleanField(default=True) #英雄性别
    isDelete = models.BooleanField(default = False) #逻辑删除
    hcontent = models.CharField(max_length=100) #英雄描述信息
    hbook = models.ForeignKey('BookInfo') #英雄与图书表的关系为一对多，所以属性定义在英雄模型中

class AreaInfo(models.Model):
    atitle=models.CharField(max_length=30) #名称
    aParent=models.ForeignKey('self',null=True,blank=True) #关系

django/pytest/test2/booktest/views.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from booktest.models import BookInfo,HeroInfo
from django.db.models import F,Q,Sum,Count
from booktest.models import AreaInfo


def index(request):
    str='%s<br>%s'%(request.path,request.encoding)
    return HttpResponse(str)

# def index1(request,value1,value2):
#     context = {'v1':value1,'v2':value2}
#     return render(request,'booktest/index.html',context)

def index2(request,parameter1,parameter2):
    context1 = {'val01':parameter1,'val02':parameter2}
    return render(request, 'booktest/index.html',context1)

def method1(request):
    return render(request,'booktest/method1.html')

def method2(request):
    return HttpResponse(request.method)

def method3(request):
    return HttpResponse(request.method)

def get(request):
    # 通过GET属性获取地址栏上的数据，获取的QueryDict对象
    dict = request.GET

    a = dict.getlist('a') #返回所有值
    b = dict.get('b')

    context = {'a':a, 'b':b}
    return render(request,'booktest/get.html',context)

def getwish(request):
    dict = request.GET
    name = dict.get('name')
    list = dict.getlist('a')
    textlist = ['生日快乐','节日快乐','学习进步','四季平安']
    str = ''
    for i in list:
        str += textlist[int(i)]+ ' '
    context = {'name':name,'wish' : str}
    return render(request,'booktest/getwish.html',context)

def post(request):
    return render(request, 'booktest/post.html')

def post1(request):
    dict = request.POST
    username = dict.get('username')
    password = dict.get('password')
    gender = dict.get('gender')
    hobby = dict.getlist('hobby')#一键多值
    context = {
        'name':username,
        'pwd':password,
        'gender':gender,
        'hobby':hobby
    }
    return render(request,'booktest/post1.html',context)

def json1(request):
    return render(request,'booktest/json.html')

def json2(request):
    books = BookInfo.objects.all()
    list = []
    for book in books:
        list.append({'btitle':book.btitle,'bpub_date':book.bpub_date})
    return JsonResponse({'list':list})
# # 定义对象，设置cookie
# def setcookie(request):
#     request = HttpResponse('设置cookie')
#     response.set_cookie('num01',123)

#     return response

# def getcookie(request):
#     cookie = request.COOKIES
#     str=''
#     if 'num01' in cookie:
#         str = 'cookie的值是：'+cookie['num01']
#     else:
#         str = '没有cookie'

#     return HttpResponse
        

def booklist(request):
    # 1.获取所有图书
    books1 = BookInfo.objects.all()
    books1 = BookInfo.objects.shuminghao(books1)
    # 2.查询所有未逻辑删除的数据
    books2 = BookInfo.objects.total()
    # 3.查询id==1的数据
    books3 = BookInfo.objects.filter(id__exact=1) #等价于filter(id=1)
    # 4.模糊查询书名包含'传'的数据
    books4 = BookInfo.objects.filter(btitle__contains='传')
    # 5.模糊查询书名以”湖“结尾的书名
    books5 = BookInfo.objects.filter(btitle__endswith='湖')
    # 6.查询备注不为空的图书数据
    books6 = BookInfo.objects.filter(bcontext__isnull=False)
    # 7.范围查询，查询图书编号为1，3的数据
    books7 = BookInfo.objects.filter(id__in=[1,3])
    # 8.查询图书编号大于3的数据
    books8 = BookInfo.objects.filter(id__gt=3)
    # 9.查询发布日期为1986年的图书
    books9 = BookInfo.objects.filter(bpub_date__year=1986)
    # 10.查询id!=3的图书信息
    books10 = BookInfo.objects.exclude(id=3)
    # 11.查询阅读量大于等于评论量的图书信息
    books11 = BookInfo.objects.filter(bread__gte=F('bcommet'))
    # 12.查询id大于3且阅读量大于30的图书信息
    books12 = BookInfo.objects.filter(Q(id__gt=3)&Q(bread__gt=30))
    # 13.查询所有图书从大到小排列
    books13 = BookInfo.objects.all().order_by('-id')
    # 14.把id大于1的图书信息按阅读量从大到小排序显示
    books14 = BookInfo.objects.filter(id__gt=1).order_by('-bread')
    # 15.查询所有图书阅读量的总和
    books15 = BookInfo.objects.aggregate(Sum('bread'))['bread__sum']
    # 16.查询图书，要求图书中英雄的描述包含'十'
    books16 = BookInfo.objects.filter(heroinfo__hcontent__contains='十')
    # 17.
    

    context = {
        'books1':books1,
        'books2':books2,
        'books3':books3,
        'books4':books4,
        'books5':books5,
        'books6':books6,
        'books7':books7,
        'books8':books8,
        'books9':books9,
        'books10':books10,
        'books11':books11,
        'books12':books12,
        'books13':books13,
        'books14':books14,
        'books15':books15,
        'books16':books16
        }
    return render(request,'booktest/booklist.html',context)

def area(request):
    area = AreaInfo.objects.get(atitle='广州市')
    return render(request,"booktest/area.html",{'area':area})

django/pytest/test2/templates/booktest/area.html
<html>

<head>
    <title>地区</title>
</head>

<body>
    <h1>当前地区：{{area.atitle}}</h1>
    <hr>
    <h2>上级地区：{{area.aParent.atitle}}</h2>
    <hr> 下级地区：
    <ul>
        {%for a in area.areainfo_set.all%}
        <li>{{a.atitle}}</li>
        {%endfor%}
    </ul>
</body>

</html>

django/pytest/test2/templates/booktest/booklist.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .list {
            width: 600px;
            border: 1px solid #bbbbbb;
            border-collapse: collapse
        }
        
        .list td {
            padding: 10px;
            border: 1px solid #bbbbbb;
        }
        
        .list th {
            padding: 10px;
            border: 1px solid #bbbbbb;
            font-weight: normal
        }
    </style>
</head>

<body>
    <p>1.显示所有图书</p>
    <table class="list">
        {% for book in books1 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
        </tr>
        {% endfor %}
    </table>
    <p>2.显示未逻辑删除的图书</p>
    <table class="list">
        {% for book in books2 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
        </tr>
        {% endfor %}
    </table>
    <p>3.id==1</p>
    <table class="list">
        {% for book in books3 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
        </tr>
        {% endfor %}
    </table>
    <p>4.书名包含"传"的所有数据</p>
    <table class="list">
        {% for book in books4 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
        </tr>
        {% endfor %}
    </table>
    <p>5.书名以"湖"结尾的所有数据</p>
    <table class="list">
        {% for book in books5 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
        </tr>
        {% endfor %}
    </table>
    <p>6.备注不为空的图书数据</p>
    <table class="list">
        {% for book in books6 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
            <td>{{book.bcontext}}</td>
        </tr>
        {% endfor %}
    </table>
    <p>7.查询id为1，3的图书信息</p>
    <table class="list">
        {% for book in books7 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
            <td>{{book.bcontext}}</td>
        </tr>
        {% endfor %}
    </table>
    <p>8.查询编号大于3的图书信息</p>
    <table class="list">
        {% for book in books8 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
            <td>{{book.bcontext}}</td>
        </tr>
        {% endfor %}
    </table>
    <p>9.查询发布时间为1986年的图书</p>
    <table class="list">
        {% for book in books9 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
            <td>{{book.bcontext}}</td>
        </tr>
        {% endfor %}
    </table>
    <p>10.查询id不等于3的图书信息</p>
    <table class="list">
        {% for book in books10 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
            <td>{{book.bcontext}}</td>
        </tr>
        {% endfor %}
    </table>
    <p>11.阅读量大于评论量的图书信息</p>
    <table class="list">
        {% for book in books11 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
            <td>{{book.bcontext}}</td>
        </tr>
        {% endfor %}
    </table>
    <p>12.查询id大于3且阅读量大于30的图书信息</p>
    <table class="list">
        {% for book in books12 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
            <td>{{book.bcontext}}</td>
        </tr>
        {% endfor %}
    </table>
    <p>13.查询所有图书信息，按照id从大到小进行排序</p>
    <table class="list">
        {% for book in books13 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
            <td>{{book.bcontext}}</td>
        </tr>
        {% endfor %}
    </table>
    <p>14.id大于1的图书信息按阅读量从达到小排序显示</p>
    <table class="list">
        {% for book in books14 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <th>{{book.bcommet}}</th>
            <th>{{book.bread}}</th>
            <td>{{book.bpub_date}}</td>
            <th>{{book.isDelete}}</th>
            <td>{{book.bcontext}}</td>
        </tr>
        {% endfor %}
    </table>
    <p>15.查询所有图书阅读量的总和</p>
    <table class="list">
        <tr>
            <td>阅读量总和：{{books15}}</td>
        </tr>
    </table>
    <p>16.查询图书，要求图书中英雄的描述包含'十'</p>
    <table class="list">
        {% for book in books16 %}
        <tr>
            <th>{{book.id}}</th>
            <td>{{book.btitle}}</td>
            <!-- <th>{{heroinfo.hname}}</th>
            <td>{{heroinfo.hcontent}}</td> -->
        </tr>
        {% endfor %}
    </table>
</body>

django/pytest/test2/templates/booktest/get.html
<html>

<head>
    <title>HttpRequest对象的GET属性</title>
</head>

<body>
    <span>{{a}}</span>
    <br>
    <span>{{b}}</span>
</body>

</html>

django/pytest/test2/templates/booktest/getwish.html
<html>

<head>
    <title>Title</title>
</head>

<body>
    <h2>祝：{{ name }}</h2>
    <h1>{{wish}}</h1>
</body>

</html>

django/pytest/test2/templates/booktest/index.html
<html>

<head>
    <title>获取url</title>
</head>

<body>
    <h2>hello world!</h2>

    <h3>使用位置参数获取URL的value</h3>
    <span>v1:{{v1}}&nbsp; v2:{{v2}}</span>
    <br>
    <h3>使用关键字参数获取URL的value</h3>
    <span>param1:{{val01}} &nbsp; param2: {{val02}}</span>
</body>

</html>

django/pytest/test2/templates/booktest/json.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script>
        $(function() {
            $('#btn').click(function() {
                $.ajax({
                    'url': '/json2/',
                    'type': 'get',
                    'dateType': 'json'
                }).done(function(dat) {
                    // console.log(dat.list)
                    var list = dat.list;
                    var str = '';
                    for (var i = 0; i < list.length; i++) {
                        str += '<li>' + list[i].btitle + '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' + list[i].bpub_date + '</li>';
                    }
                    $('.list').html(str);
                }).fail(function() {
                    alert('服务器超时，请重试')
                })
            })
        })
    </script>
    <title>Document</title>
</head>

<body>
    <h2>图书列表</h2>
    <input type="button" value="显示" id="btn">
    <ul class="list"></ul>
</body>

</html>

django/pytest/test2/templates/booktest/method1.html
<html>

<head>
    <title>方法练习</title>
</head>

<body>
    <a href="/method2/">方式一：get</a>
    <br>
    <br>
    <br>
    <form action="/method3/" method="post">
        <input type="submit" value="方式二：post">
    </form>
</body>

</html>

django/pytest/test2/templates/booktest/post.html
<html>

<head>
    <title>POST属性</title>
</head>

<body>
    <h2>用户注册</h2>
    <form action="/post1/" method="post">
        <p>
            <label>姓&nbsp;&nbsp;&nbsp;名：</label><input type="text" name="username" />
        </p>
        <p>
            <label>密&nbsp;&nbsp;&nbsp;码：</label><input type="password" name="password" />
        </p>
        <p>
            <label>性&nbsp;&nbsp;&nbsp;别：</label>
            <input type="radio" name="gender" value="男" /> 男
            <input type="radio" name="gender" value="女" /> 女
        </p>
        <p>
            <label>爱好：</label>
            <input type="checkbox" name="hobby" value="唱歌" /> 唱歌
            <input type="checkbox" name="hobby" value="跑步" /> 跑步
            <input type="checkbox" name="hobby" value="游泳" /> 游泳
            <input type="checkbox" name="hobby" value="足球" /> 足球
        </p>
        <p>
            <input type="submit" name="" value="提交">
            <input type="reset" name="" value="重置">
        </p>
    </form>
</body>

</html>

django/pytest/test2/templates/booktest/post1.html
<head>
    <title>POST属性</title>
</head>

<body>
    <ul>
        <li>{{ name }}</li>
        <li>{{ pwd }}</li>
        <li>{{ gender }}</li>
        <li>{{ hobby }}</li>
    </ul>
</body>

</html>