django/myblog/myblog/blog/urls.py
from django.conf.urls import url
from blog.views import IndexView,ArticleDetailView,CategoryView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^article/(?P<article_id>\d+)$', ArticleDetailView.as_view(), name='detail'),
    url(r"^category/(?P<cate_id>\d+)$", CategoryView.as_view(), name='category')
]

django/myblog/myblog/myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls',namespace='blog')),#博客
]

django/myblog/myblog/blog/models.py
from django.db import models
from db.base_model import BaseModel

class Article(BaseModel):
    '''定义文章模型类'''
    # 文章的状态
    STATUS_CHOICES = (
        ('d','part'),
        ('p','Published'),
    )
    title = models.CharField(max_length=70,verbose_name="'标题'")
    body = models.TextField(verbose_name='正文')

    status = models.CharField(max_length=1,choices=STATUS_CHOICES,verbose_name="文章状态")
    abstract = models.CharField(max_length=54,blank=True,null=True,verbose_name="摘要",help_text="可选项，若为空格则摘取正文前54个字符")

    # 阅读量
    views = models.PositiveIntegerField(default=0,verbose_name="浏览器")
    # 点赞数
    likes = models.PositiveIntegerField(default=0,verbose_name="点赞数")
    # 是否置顶
    topped = models.BooleanField(default=False,verbose_name="置顶")
    # 目录分类
    category = models.ForeignKey('Category',verbose_name="分类",null=True,on_delete=models.SET_NULL)

    class Meta:
        db_table = 'blog_article'
        verbose_name = '文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

class Category(BaseModel):
    '''文章分类模型类'''
    name = models.CharField(max_length=20,verbose_name="类名")

    class Meta:
        db_table = 'blog_category'
        verbose_name = '文章分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

class BlogComment(BaseModel):
    '''用户评论模型类'''
    user_name = models.CharField(max_length=100,verbose_name="评论者的名字")
    user_email = models.EmailField(max_length=255,verbose_name="评论者邮箱")
    body = models.TextField(verbose_name="评论内容")
    # create_time = models.DateTimeField(verbose_name="评论发表时间",auto_now_add=True)
    article = models.ForeignKey('Article',verbose_name="评论所属文章",on_delete=models.CASCADE)

    class Meta:
        db_table = 'blog_comment'
        verbose_name = '文章评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.body[:20]

django/myblog/myblog/blog/forms.py
from django import forms
from blog.models import Article,BlogComment

class BlogCommentForm(forms.ModelForm):
    '''forms用户评论模型类'''
    class Meta:
        model = BlogComment
        fields = ['user_name','user_email','body']

        widgets = {
            'user_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': '请输入昵称',
                'aria-describedby': 'sizing-addon1',
            }),
            'user_email': froms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': '请输入邮箱',
                'aria-describedby': 'sizing-addon1',
            }),
            'body': forms.Textarea(attrs={'placeholder':'让我来说两句'})
        }

django/myblog/myblog/blog/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from blog.models import Article,Category
from blog.forms import BlogCommentForm
import markdown2

class IndexView(ListView):
    '''博客首页'''
    # 制定获取的model数据列表的名字
    # context_object_name = 'article_list'

    def get(self,request):
        '''获取已发布的文章列表，并转为html格式'''
        article_list = Article.objects.filter(status='p')
        for article in article_list:
            article.body = markdown2.markdown(article.body,)
        return render(request,'index.html',{'article_list':article_list})
    
    # 为上下文添加额外的变量，以便在模板中访问
    def get_context_data(self,**kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        return super(IndexView, self).get_context_data(**kwargs)

class ArticleDetailView(DetailView):
    '''显示文章详情'''
    model = Article
    template_name = 'detail.html'
    context_object_name = "article"

    # pk_url_kwarg用于接受来自url中的参数作为主键
    pk_url_kwarg = 'article_id'

    # 从数据库中获取id为pk_url_kwargs的对象
    def get_object(self, queryset=None):
        obj = super(ArticleDetailView, self).get_object()
        obj.body = markdown2.markdown(obj.body)
        return obj

class CategoryView(ListView):
    '''文章分类'''
    def get(request,self):
        category = request.cate_id
        article_list = Article.objects.filter(category=category,status='p')
        for article in article_list:
            article.body = markdown2.markdown(article.body,)
        return render(request,'index.html',{'article_list':article_list})   
    
    # 为上下文添加额外的变量，以便在模板中访问
    def get_context_data(self,**kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        return super(IndexView, self).get_context_data(**kwargs)

django/myblog/myblog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content=""> {% block title %}{% endblock %}

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--&lt;!&ndash;[if lt IE 9]>-->
    <!--<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>-->
    <!--<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>-->
    <!--<![endif]&ndash;&gt;-->

</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}">主页</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">关于</a>
                    </li>
                    <li>
                        <a href="#">联系我</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    {% block content %}{% endblock content %}

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p style="text-align: center;">Copyright &copy; kkxiami's blog 2018</p>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

django/myblog/myblog/templates/detail.html
{% extends 'base.html' %} {% block content %}

<div class="'container">
    <div class="row">
        <div class="col-md-8">
            <div class="text-center">
                <h2><a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a></h2>
                <p><span class="glyphicon glyphicon-time"></span> {{ article.created_time }}</p>
                <br>
                <p class="lead">{{ article.body | safe}}</p>
            </div>
            <div>

            </div>
        </div>

        <!-- 博客旁列 -->
        <div class="col-md-4">
            <!-- Blog Search Well -->
            <div class="well">
                <h4>Blog Search</h4>
                <div class="input-group">
                    <input type="text" class="form-control">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <span class="glyphicon glyphicon-search"></span>
                    </button>
                    </span>
                </div>
                <!-- /.input-group -->
            </div>

            <!-- Blog Categories Well -->
            <div class="well">
                <h4>博客目录</h4>
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            {% for category in category_list %}
                            <li class="cat-item"><a href="{% url 'app:category' category.pk %}">{{ category.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <!-- /.row -->
            </div>

            <!-- Side Widget Well -->
            <div class="well">
                <h4>Side Widget Well</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

django/myblog/myblog/templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="container">

    <div class="row">

        <!-- 博客页面实体 -->
        <div class="col-md-8">
            <!-- 博客正文实体 -->
            <!-- <h1 class="page-header">
            </h1> -->

            <!-- 博客正文 -->
            <div>
                {% for article in article_list %}
                <h2>
                    <a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a>
                </h2>
                <p class="lead">
                    by <a href="index.php">KK虾米</a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> {{ article.created_time }}</p>
                <hr>
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <hr>
                <p>{{ article.body | safe }}</p>
                <a class="btn btn-primary" href="{% url 'blog:detail' article.pk %}">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
                <span class="comments-link"><a href="#">{{ num_comments }} 评论</a></span>
                <span class="post-views"><a href="#">{{ article.views }} 阅读</a></span>
                <hr> {% endfor %}
            </div>
            <div>
                {% include 'pagination.html' %}
            </div>

        </div>

        <!-- 博客旁列 -->
        <div class="col-md-4">

            <!-- Blog Search Well -->
            <div class="well">
                <h4>Blog Search</h4>
                <div class="input-group">
                    <input type="text" class="form-control">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <span class="glyphicon glyphicon-search"></span>
                    </button>
                    </span>
                </div>
                <!-- /.input-group -->
            </div>

            <!-- Blog Categories Well -->
            <div class="well">
                <h4>博客目录</h4>
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            {% for category in category_list %}
                            <li class="cat-item"><a href="{% url 'app:category' category.pk %}">{{ category.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <!-- /.row -->
            </div>

            <!-- Side Widget Well -->
            <div class="well">
                <h4>Side Widget Well</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
            </div>

        </div>

    </div>
    <!-- /.row -->

</div>

{% endblock content %}

django/myblog/myblog/templates/pagination.html
<ul class='pagination pagination-lg'>
    {% if article_list.has_previous %}
    <li><a href="?page={{ article_list.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li><a class="'disabled">&laquo;</a></li>
    {% endif %} {% for page in pages %}
    <li><a href="?page={{ page }}">{{ page }}</a></li>
    {% endfor %} {% if article_list.has_next %}
    <li><a href="?page={{ article_list.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li><a class="'disabled">&raquo;</a></li>
    {% endif %}
</ul>