django/pytest/dailyfresh/apps/cart/urls.py
from django.conf.urls import url
from cart.views import CartAddView,CartInfoView,CartUpdateView,CartDeleteView

urlpatterns = [
    url(r'^$',CartInfoView.as_view(),name='show'),#购物车页面的显示
    url(r'^add$',CartAddView.as_view(),name='add'), #购物车添加
    url(r'^update$',CartUpdateView.as_view(),name='update'),#购物车页面的更新
    url(r'^delete$',CartDeleteView.as_view(),name='delete'),#购物车记录的删除
]

django/pytest/dailyfresh/apps/goods/urls.py
from django.conf.urls import url
from goods.views import IndexView,DetailView,ListView

urlpatterns = [
    url(r'^index$', IndexView.as_view(), name = 'index'),#首页
    url(r'^goods/(?P<sku_id>\d+)$',DetailView.as_view(),name='detail'), #商品详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$',ListView.as_view(),name='list'),#商品列表
]

django/pytest/dailyfresh/apps/user/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required #login_required装饰器
from user.views import RegisterView,ActiveView,LoginView,LogoutView,UsercenterView,UserorderView,UsersiteView

urlpatterns = [
    url(r'^register$',RegisterView.as_view(),name='register'),#注册
    url(r'^active/(?P<token>.*)$',ActiveView.as_view(),name = 'active'),#激活，token做为关键字参数
    url(r'^login$',LoginView.as_view(),name = 'login'),#登录
    url(r'^logout$',LogoutView.as_view(),name = 'logout'),#登出
    # url(r'^usercenter$',login_required(UsercenterView.as_view()),name = 'usercenter'),#用户中心
    # url(r'^userorder$',login_required(UserorderView.as_view()),name = 'userorder'),#用户订单
    # url(r'^usersite$',login_required(UsersiteView.as_view()),name = 'usersite'),#用户收货地址

    url(r'^usercenter$',UsercenterView.as_view(),name = 'usercenter'),#用户中心
    url(r'^userorder/(?P<page>\d+)$',UserorderView.as_view(),name = 'userorder'),#用户订单
    url(r'^usersite$',UsersiteView.as_view(),name = 'usersite'),#用户收货地址
]

# 重写View的as_view方法，在重写的方法中返回login_required,在路由中使用的还是之前的方法：类名.as_view()的形式

django/pytest/dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/',include('tinymce.urls')),#富文本编辑器
    url(r'^search',include('haystack.urls')),
    url(r'^user/',include('user.urls',namespace='user')),#用户模块
    url(r'^cart/',include('cart.urls',namespace='cart')),#购物车模块
    url(r'^order/',include('order.urls',namespace='order')),#订单模块
    url(r'^',include('goods.urls',namespace='goods')),#商品模块
]

django/pytest/dailyfresh/apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin

# 前端采用ajax post请求
# 需要传递的参数：商品id(sku_id) 商品数目（count）
class CartAddView(View):
    '''购物车记录添加'''
    def post(self,request):
        '''记录添加'''
        # 判断用户是否登录
        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            return JsonResponse({'res':0,'errmsg':'用户未登录'})

        # 接收参数
        sku_id = request.POST.get('sku_id')
        count = int(request.POST.get('count'))
        
        # 参数校验
        if not all([sku_id,count]):
            return JsonResponse({'res':1,'errmsg':'数据不完整'})
        # 校验商品id
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except Exception as e:
            # 商品数目非法
            return JsonResponse({'res':3,'errmsg':'商品信息错误'})
        # 校验商品的数目
        try:
            count = count
        except Exception as e:
            return JsonResponse({'res':3,'errmsg':'商品数目非法'})

        if count <= 0:
            # 商品数目非法
            return JsonResponse({'res':4,'errmsg':'商品数量不合法'})
        # 业务处理，购物车添加

        # 如果用户购物车中已经添加过该商品，需要进行数目累加（从redis中获取）
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        # 先尝试从cart_key对应的hash元素中获取属性sku_id的值
        cart_count = conn.hget(cart_key,sku_id)
        if cart_count:
            # 用户购物车中已经添加过该商品，数目需要累加
            count += int(cart_count)
        # 判断商品的库存
        if count > sku.stock:
            return JsonResponse({ 'res':5,'errmsg':'商品库存不足' })

        # 设置用户购物车中商品的数目
        conn.hset(cart_key,sku_id,count)

        # 获取用户购物车中商品的条目数
        cart_count = conn.hlen(cart_key)
        print('******',cart_count)
        # 返回应答
        return JsonResponse({ 'res':6,'cart_count':cart_count,'message':'添加记录成功' })

# /cart/
class CartInfoView(LoginRequiredMixin,View):
    '''购物车页面显示'''
    def get(self,request):
        '''显示'''
        # 获取登录的用户
        user = request.user

        # 获取用户购物车中的记录信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        cart_dict = conn.hgetall(cart_key) #{商品id：商品数量}
        print('********',cart_dict)

        skus = []
        total_count = 0
        total_price = 0
        # 遍历获取商品的信息
        for sku_id, count in cart_dict.items():
            print('#############',sku_id)
            # 根据商品的id获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price*int(count)
            # 给sku增加属性count,amount,分别保存用户购物车中添加的商品的数目和商品的小计
            sku.count = count
            sku.amount = amount
            # 添加商品
            skus.append(sku)

            # 累加计算用户购物车中商品的总数目的总价格
            total_count += int(count)
            total_price += amount

            # 组织模板上下文
            context = {
                'total_count':total_count,
                'total_price':total_price,
                'skus':skus
            }

        # 使用模板
        return render(request,'cart.html',context)


# /cart/update
#前端采用ajax post请求
class CartUpdateView(View):
    def post(self,request):
        '''更新'''
        # 判断用户是否登录
        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            return JsonResponse({'res':0,'errmsg':'用户未登录'})
        # 接收参数
        sku_id = request.POST.get('sku_id')
        print('sku_id:')
        count = request.POST.get('count')
        # 参数校验
         # 参数校验
        if not all([sku_id,count]):
            return JsonResponse({'res':1,'errmsg':'数据不完整'})
        # 校验商品id是否存在
        try:
            sku = GoodsSKU.objects.get(id = sku_id)            
        except Exception as e:
            # 商品数目非法
            return JsonResponse({'res':3,'errmsg':'商品信息错误'})
        print('*****',sku.name,'########')
        # 校验商品的数目是否合法
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res':4,'errmsg':'商品的数目不合法'})

        if count <= 0:
            return JsonResponse({'res':5,'errmsg':'商品的数目不合法'})

        # 业务处理：购物车记录的更新
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        # 判断商品的数目是否大于商品的库存:
        if count > sku.stock:
            return JsonResponse({'res':5,'errmsg':'商品库存不足'})

        #更新redis中的记录
        conn.hset(cart_key,sku_id,count)

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({'res':6,'total_count':total_count,'message':'信息更新成功'})

# /cart/delete
# 前端采用ajax post请求
# 需要传递的参数：商品的id(sku_id)
class CartDeleteView(View):
    '''购物车记录的删除'''
    def post(self,request):
        # 删除购物车记录
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':0,'errmsg':'用户未登录'})

        # 获取参数
        sku_id = request.POST.get('sku_id')
        
        if not all([sku_id]):
            return JsonResponse({'res':1,'errmsg':'参数不完整'})

        # 校验商品的id
        try:
            sku =  GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res':2,'errmsg':'商品不存在'})

        # 业务处理：购物车记录删除
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        # 删除redis中对应的记录
        conn.hdel(cart_key,sku_id)

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)
        # 返回应答
        return JsonResponse({'res':3,'total_count':total_count,'message':'删除成功'})

django/pytest/dailyfresh/templates/base.html
{# 注册 登录 首页 详情页 列表页 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- 网页顶部引入文件块 -->
    {% block topfiles %}{% endblock topfiles %}
</head>

<body>
    <!-- 注册和登录页面没有此欢迎信息，用块包起来，注册登录页面继承此页面时可以将此块置空 -->
    {% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                <!-- 记录用户登录状态 -->
                {% if user.is_authenticated %}
                <div class="login_btn fl">
                    欢迎您：<em>{{ user.username}}</em>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}">退出登录</a>
                </div>
                {% else %}
                <div class="login_btn fl">
                    <a href="{% url 'user:login'%}">登录</a>
                    <span>|</span>
                    <a href="{% url 'user:register' %}">注册</a>
                </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:usercenter' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:show' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:userorder' 1 %}">我的订单</a>
                    <span>|</span>
                    <a href="{% url 'goods:index' %}">首页</a>
                </div>
            </div>
        </div>
    </div>
    {% endblock header_con %}
    <!-- {# 网页搜索块 #} -->
    {% block search_bar %}
    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
        <div class="guest_cart fr">
            <a href="#" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
        </div>
    </div>
    {% endblock search_bar %}
    <!-- {#主体内容块#} -->
    {% block body %}{% endblock body %}
    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
    <!-- {# 网页底部html元素块 #} -->
    {% block bottom %}{% endblock bottom %}
    <!-- {#网页底部文件块#} -->
    {% block bottomfiles %}{% endblock bottomfiles %}
</body>

</html>

django/pytest/dailyfresh/templates/base_detail_list.html
{% extends 'base.html' %} {% block body %}
<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                {% for type in types %}
                <li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>
<!-- {# 详情页，列表页主体内容块 #}  -->
{% block main_content %}{% endblock main_content %}
<!--  -->
{% endblock body %}

django/pytest/dailyfresh/templates/detail.html
{% extends 'base_detail_list.html' %} {% load staticfiles %}
<!--  -->
{% block title %}天天生鲜-商品详情{% endblock title %}
<!--  -->
{% block main_content %}
<div class="breadcrumb">
    <a href="#">全部分类</a>
    <span>></span>
    <a href="#">{{ sku.type.name }}</a>
    <span>></span>
    <a href="#">商品详情</a>
</div>

<div class="goods_detail_con clearfix">
    <div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

    <div class="goods_detail_list fr">
        <h3>{{ sku.name }}</h3>
        <p>{{ sku.desc }}</p>
        <div class="prize_bar">
            <span class="show_pirze">¥<em>{{ sku.price }}</em></span>
            <span class="show_unit">单  位：{{ sku.unite }}</span>
        </div>
        <div class="goods_num clearfix">
            <div class="num_name fl">数 量：</div>
            <div class="num_add fl">
                <input type="text" class="num_show fl" value="1">
                <a href="javascript:;" class="add fr">+</a>
                <a href="javascript:;" class="minus fr">-</a>
            </div>
        </div>
        <div>
            <div>其他规格：</div>
            <div>
                {% for sku in same_spu_skus %}
                <a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a> {% empty %}暂无其他规格商品{% endfor %}
            </div>
        </div>
        <div class="total">总价：<em>{{ sku.price }}元</em></div>
        <div class="operate_btn">
            {% csrf_token %}
            <a href="javascript:;" class="buy_btn">立即购买</a>
            <a href="javascript:;" sku_id='{{ sku.id }}' class="add_cart" id="add_cart">加入购物车</a>
        </div>
    </div>
</div>

<div class="main_wrap clearfix">
    <div class="l_wrap fl clearfix">
        <div class="new_goods">
            <h3>新品推荐</h3>
            <ul>
                {% for sku in new_skus %}
                <li>
                    <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                    <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                    <div class="prize">{{ sku.price }}</div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="r_wrap fr clearfix">
        <ul class="detail_tab clearfix">
            <li class="active">商品介绍</li>
            <li>评论</li>
        </ul>

        <div class="tab_content">
            <dl>
                <dt>商品详情：</dt>
                <dd>{{ sku.goods.detail|safe }}</dd>
            </dl>
        </div>
        <!-- 显示商品的评论信息 -->
        <div class="tab_content" style="display:none">
            {% for order_sku in order_skus %}
            <dl>
                <dt>评论时间：{{ order_sku.update_time }}&nbsp;&nbsp;评论用户:{{ order_sku.order.user.username }}</dt>
                <dd>评论内容：{{ order_sku.comment }}</dd>
            </dl>
            {% empty %}暂无评论信息{% endfor %}
        </div>
    </div>
</div>
{% endblock main_content %}
<!--  -->
{% block bottom %}
<div class="add_jump"></div>{% endblock bottom %}
<!--  -->
{% block bottomfiles %}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript">
    // 计算商品的总价
    function update_sku_amount() {
        // 获取商品的价格和数量
        var price = $('.show_pirze').children('em').text()
        var count = $('.num_show').val()
            // 计算小计
        var amount = parseFloat(price) * parseInt(count)
            // 返回总价格
        $('.total').children('em').text(amount.toFixed(2) + '元')
    }
    // 商品数目的增加
    $('.add').click(function() {
            // 获取商品的数目
            var count = $('.num_show').val()
                // 数目加1
            count = parseInt(count) + 1
                // 重新设置商品数目
            $('.num_show').val(count)
                // 更新商品小计
            update_sku_amount()
        })
        // 商品数目的减少
    $('.minus').click(function() {
            var count = $('.num_show').val()
            count = parseInt(count) - 1
            if (count <= 0) {
                return
            }
            $('.num_show').val(count)
            update_sku_amount()
        })
        // 用户手动输入商品的数目，blur()失去焦点函数
    $('.num_show').blur(function() {
        // 获取用户输入的商品的数目
        var count = $('.num_show').val()
            // 判断用户是否合法
        if (isNaN(count) || count.trim().length == 0 || parseInt(count) <= 0) {
            count = 1
        }
        // 更新商品数目
        $('.num_show').val(parseInt(count))
            // 计算商品总价格
        update_sku_amount()

    })

    // 获取add_cart左上角的坐标
    var $add_x = $('#add_cart').offset().top;
    var $add_y = $('#add_cart').offset().left;

    var $to_x = $('#show_count').offset().top;
    var $to_y = $('#show_count').offset().left;



    // 购物车记录的添加
    $(".add_cart").click(function() {
        // 获取商品的id和商品的数目
        var count = $('.num_show').val()
        var sku_id = $(this).attr('sku_id') //attr:获取自定义属性；prop:获取原有属性
        var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
        var params = {
                'sku_id': sku_id,
                'count': count,
                'csrfmiddlewaretoken': csrf
            }
            // 发起ajax post请求，访问/cart/add,传递的参数：商品id(sku_id) 商品数目(count)
        $.post('/cart/add', params, function(data) {
            if (data.res == 6) {
                // 添加购物车记录成功
                $(".add_jump").css({
                    'left': $add_y + 80,
                    'top': $add_x + 10,
                    'display': 'block'
                })
                $(".add_jump").stop().animate({
                        'left': $to_y + 7,
                        'top': $to_x + 7
                    },
                    "fast",
                    function() {
                        $(".add_jump").fadeOut('fast', function() {
                            // 设置用户购物车中的条目数
                            $('#show_count').html(data.cart_count);
                        });

                    });
            } else {
                alert(data.errmsg)
            }
        })
    })
</script>
{% endblock bottomfiles %}
</body>

</html>

django/pytest/dailyfresh/templates/index.html
{% extends 'base.html' %} {% load staticfiles %}
<!--  -->
{% block title %}首页{% endblock title %}
<!--  -->
{% block topfiles %}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
<!--  -->
{% block body %}
<div class="navbar_con">
    <div class="navbar">
        <h1 class="fl">全部商品分类</h1>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>

<div class="center_con clearfix">
    <ul class="subnav fl">
        {% for type in types %}
        <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
        {% endfor %}
    </ul>
    <div class="slide fl">
        <ul class="slide_pics">
            {% for banner in goods_banner %}
            <li>
                <a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a>
            </li>
            {% endfor %}
        </ul>
        <div class="prev"></div>
        <div class="next"></div>
        <ul class="points"></ul>
    </div>
    <div class="adv fl">
        {% for banner in promotion_banner %}
        <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
        {% endfor %}
    </div>
</div>
{% for type in types %}
<div class="list_model">
    <div class="list_title clearfix">
        <h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
        <div class="subtitle fl">
            <span>|</span> {# type种类首页展示的文字商品信息 #} {% comment %} {% for banner in type_goods_banner %} {% if banner.type == type and banner.display_type == 0 %}
            <a href="#">鲜芒</a> {% endif %} {% endfor %}{% endcomment %}
            <!--  -->
            {% for banner in type.title_banner %}
            <a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a> {% endfor %}
        </div>
        <a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
    </div>

    <div class="goods_con clearfix">
        <div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
        <ul class="goods_list fl">
            {# type种类首页展示的图片商品信息 #} {% for banner in type.image_banner %}
            <li>
                <h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
                <a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
                <div class="prize">¥ {{ banner.sku.price }}</div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endfor %} {% endblock body %}
<!--  -->
{% block bottomfiles %}
<script type="text/javascript" src="js/slideshow.js"></script>
<script type="text/javascript">
    BCSlideshow('focuspic');
    var oFruit = document.getElementById('fruit_more');
    var oShownum = document.getElementById('show_count');

    var hasorder = localStorage.getItem('order_finish');

    if (hasorder) {
        oShownum.innerHTML = '2';
    }

    oFruit.onclick = function() {
        window.location.href = 'list.html';
    }
</script>
{% endblock bottomfiles %}

django/pytest/dailyfresh/templates/login.html
{% extends 'base.html' %}
<!--  -->
{% load staticfiles %}
<!--  -->
{% block title %}天天生鲜-登录{% endblock title %}
<!--  -->
{% block header_con %}{% endblock header_con %}
<!--  -->
{% block search_bar %}{% endblock search_bar %}
<!--  -->
{% block body %}
<div class="login_top clearfix">
    <a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
</div>

<div class="login_form_bg">
    <div class="login_form_wrap clearfix">
        <div class="login_banner fl"></div>
        <div class="slogan fl">日夜兼程 · 急速送达</div>
        <div class="login_form fr">
            <div class="login_title clearfix">
                <h1>用户登录</h1>
                <a href="{% url 'user:register' %}">立即注册</a>
            </div>
            <div class="form_input">
                {# 如果表单不设置action地址，提交表单时是向浏览器地址栏中的地址发起提交 #}
                <form method="post">
                    {% csrf_token %}
                    <input type="text" name="username" value="{{ username }}" class="name_input" placeholder="请输入用户名">
                    <div class="user_error">输入错误</div>
                    <input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
                    <div class="pwd_error">输入错误</div>
                    <div class="more_input clearfix">
                        <input type="checkbox" name="remember" {{ checked }}>
                        <label>记住用户名</label>
                        <a href="#">忘记密码</a>
                    </div>
                    <input type="submit" name="" value="登录" class="input_submit">
                </form>
            </div>
        </div>
    </div>
    {{ errmsg }}
</div>
{% endblock body %}

django/pytest/dailyfresh/templates/static_base.html
{# 注册 登录 首页 详情页 列表页 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- 网页顶部引入文件块 -->
    {% block topfiles %}{% endblock topfiles %}
</head>

<body>
    <!-- 注册和登录页面没有此欢迎信息，用块包起来，注册登录页面继承此页面时可以将此块置空 -->
    {% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                <div class="login_btn fl">
                    <a href="{% url 'user:login'%}">登录</a>
                    <span>|</span>
                    <a href="{% url 'user:register' %}">注册</a>
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:usercenter' %}">用户中心</a>
                    <span>|</span>
                    <a href="cart.html">我的购物车</a>
                    <span>|</span>
                    <a href="user_center_order.html">我的订单</a>
                </div>
            </div>
        </div>
    </div>
    {% endblock header_con %}
    <!-- {# 网页搜索块 #} -->
    {% block search_bar %}
    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="search_con fl">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
        <div class="guest_cart fr">
            <a href="#" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
        </div>
    </div>
    {% endblock search_bar %}
    <!-- {#主体内容块#} -->
    {% block body %}{% endblock body %}
    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
    <!-- {# 网页底部html元素块 #} -->
    {% block bottom %}{% endblock bottom %}
    <!-- {#网页底部文件块#} -->
    {% block bottomfiles %}{% endblock bottomfiles %}
</body>

</html>